// ==========================================================
// RuxLog Platform — PDF reports
//
// Shared by Analytics and Petty Cash, so both produce an identical
// looking report. Built with jsPDF + autotable, loaded from a CDN on
// any page that includes this file — generating a real PDF in the
// browser isn't something plain JS can do on its own.
//
// Rows must already be newest-first: this renders them and then
// hard-caps the result at maxPages, dropping anything that would have
// flowed further, so the most recent activity is always what's kept.
// Analytics uses the 2-page default; the Petty Cash report asks for 1.
// ==========================================================

function downloadPdf(filename, title, headers, rows, maxPages = 2) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: "landscape" });

  // "Generated by RuxLog" with the brand word picked out in gold, the
  // same way it's highlighted on the generated schedule. jsPDF has no
  // rich text, so it's drawn as two pieces and the second is placed
  // at the measured width of the first.
  doc.setFontSize(11);
  doc.setFont(undefined, "normal");
  doc.setTextColor(120);
  const prefix = "Generated by ";
  doc.text(prefix, 14, 13);

  doc.setFont(undefined, "bold");
  doc.setTextColor(242, 184, 75); // #f2b84b, the schedule's brand gold
  doc.text("RuxLog", 14 + doc.getTextWidth(prefix), 13);

  doc.setFont(undefined, "bold");
  doc.setTextColor(30, 58, 95); // --ruxlog-primary
  doc.setFontSize(14);
  doc.text(title, 14, 21);

  doc.setFont(undefined, "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`${new Date().toLocaleString()} — most recent first`, 14, 27);

  doc.autoTable({
    head: [headers],
    body: rows,
    startY: 32,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [30, 58, 95] }, // matches --ruxlog-primary
  });

  const totalPages = doc.internal.getNumberOfPages();
  for (let page = totalPages; page > maxPages; page--) {
    doc.deletePage(page);
  }

  doc.save(filename);
}
