// ==========================================================
// RuxLog Platform — Schedule preview (dashboard widget)
//
// Read-only mirror of the generated schedule, shown on every role's
// dashboard so everyone sees the day plan without visiting the
// Schedule feature (which still owns all the add/edit/delete
// functionality). Opens on today's schedule, with Previous/Next and
// a date picker to browse past and future planned days. Rasterized
// into a PNG via html2canvas (loaded from a CDN in dashboard.html)
// when shared to WhatsApp — there's no reasonable vanilla-JS way to
// rasterize styled DOM into an image.
// ==========================================================

let dashboardScheduleDate = toDateString(new Date());

async function renderDashboardSchedulePreview(containerEl) {
  containerEl.innerHTML = `
    <div class="schedule-preview-panel">
      <div class="schedule-toolbar">
        <button type="button" id="dash-schedule-prev-btn" class="btn-page">&#9664; Previous</button>
        <input type="date" id="dash-schedule-date-input" />
        <button type="button" id="dash-schedule-next-btn" class="btn-page">Next &#9654;</button>
      </div>
      <div class="schedule-card" id="schedule-preview">
        <h2 id="preview-title">SCHEDULE</h2>
        <hr class="schedule-divider" />
        <div id="preview-entries"></div>
        <p class="schedule-watermark">Generated by <span class="schedule-watermark-brand">RuxLog</span> ! (Ruxins Logistics) Management System.</p>
      </div>
      <button type="button" id="share-whatsapp-btn" class="btn btn-auto btn-whatsapp">Share Schedule</button>
    </div>
  `;

  document.getElementById("dash-schedule-date-input").value = dashboardScheduleDate;
  document.getElementById("dash-schedule-prev-btn").addEventListener("click", () => changeDashboardScheduleDate(-1));
  document.getElementById("dash-schedule-next-btn").addEventListener("click", () => changeDashboardScheduleDate(1));
  document.getElementById("dash-schedule-date-input").addEventListener("change", (e) => {
    dashboardScheduleDate = e.target.value;
    loadDashboardSchedule();
  });
  document.getElementById("share-whatsapp-btn").addEventListener("click", () => handleShareWhatsApp(dashboardScheduleDate));

  await loadDashboardSchedule();
}

function changeDashboardScheduleDate(deltaDays) {
  const d = new Date(dashboardScheduleDate + "T00:00:00");
  d.setDate(d.getDate() + deltaDays);
  dashboardScheduleDate = toDateString(d);
  document.getElementById("dash-schedule-date-input").value = dashboardScheduleDate;
  loadDashboardSchedule();
}

async function loadDashboardSchedule() {
  const { data, error } = await supabaseClient
    .from("schedule_entries")
    .select("*")
    .eq("schedule_date", dashboardScheduleDate)
    .order("entry_time", { ascending: true });

  const titleEl = document.getElementById("dashboard-schedule-title");
  if (titleEl) titleEl.hidden = dashboardScheduleDate !== toDateString(new Date());

  if (error) {
    document.getElementById("preview-entries").innerHTML = `<p class="empty-note">Could not load schedule: ${error.message}</p>`;
    return;
  }

  renderPreviewCard(dashboardScheduleDate, data || []);
}

function renderPreviewCard(dateStr, entries) {
  const dateObj = new Date(dateStr + "T00:00:00");
  const weekday = dateObj.toLocaleDateString(undefined, { weekday: "long" }).toUpperCase();
  document.getElementById("preview-title").textContent = `${weekday} SCHEDULE`;

  const entriesEl = document.getElementById("preview-entries");
  entriesEl.innerHTML = entries.length
    ? entries
        .map(
          (e) => `<p class="schedule-entry${e.completed ? " schedule-entry-completed" : ""}">
            <span class="entry-time">${e.completed ? "✓ " : ""}${formatEntryTime(e.entry_time)}:</span>
            <span class="entry-desc">${e.description}</span>
          </p>`
        )
        .join("")
    : `<p class="schedule-entry"><span class="entry-desc">No entries yet.</span></p>`;
}

// There is no way for a website to post directly into an existing
// WhatsApp group — that invite link only lets someone join it, and
// WhatsApp has no public API for a static site to send a message into
// a specific group on someone's behalf. This hands the schedule to the
// device's native share sheet (as an image where supported, otherwise
// just the caption text) and the user picks the group themselves —
// WhatsApp always requires that one tap, for anyone's messages, not
// just ours. Only the short caption goes along with the photo — the
// full entry list stays out of it since it's already visible in the
// image itself.
async function handleShareWhatsApp(dateStr) {
  const btn = document.getElementById("share-whatsapp-btn");
  btn.disabled = true;

  try {
    const caption = buildCaption(dateStr);

    if (navigator.share) {
      try {
        if (document.fonts && document.fonts.ready) await document.fonts.ready;

        const target = document.getElementById("schedule-preview");
        const canvas = await html2canvas(target, { backgroundColor: null, scale: 2 });
        const blob = await new Promise((resolve) => canvas.toBlob(resolve, "image/png"));
        const file = new File([blob], `schedule-${dateStr}.png`, { type: "image/png" });

        if (navigator.canShare && navigator.canShare({ files: [file] })) {
          await navigator.share({ files: [file], text: caption });
        } else {
          await navigator.share({ text: caption });
        }
        return;
      } catch (err) {
        if (err.name === "AbortError") return; // user cancelled the share sheet
        console.warn("Native share failed, falling back to WhatsApp web link:", err);
      }
    }

    // Fallback for browsers without the native share sheet (mainly desktop)
    window.open(`https://wa.me/?text=${encodeURIComponent(caption)}`, "_blank", "noopener");
  } finally {
    btn.disabled = false;
  }
}

function buildCaption(dateStr) {
  const dateObj = new Date(dateStr + "T00:00:00");
  const weekday = dateObj.toLocaleDateString(undefined, { weekday: "long" }).toUpperCase();
  const dateLabel = dateObj.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
  return `${weekday} SCHEDULE (${dateLabel})`;
}
